# Generated by Django 5.1.6 on 2025-03-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moeda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=3)),
                ('valor', models.DecimalField(decimal_places=15, max_digits=15)),
            ],
        ),
    ]
